# Generated by Django 3.1.7 on 2021-05-27 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Especialidad', models.CharField(blank=True, max_length=60, null=True, verbose_name='Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='ExpedientePaciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('ApellidoPaterno', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('ApellidoMaterno', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('Genero', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1, verbose_name='Género')),
                ('Nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('Direccion', models.CharField(max_length=80, verbose_name='Direccion')),
                ('Correo', models.EmailField(max_length=50, verbose_name='Correo electrónico')),
                ('Telefono', models.CharField(max_length=12, verbose_name='Telefono')),
                ('Alergias', models.CharField(max_length=200, verbose_name='Alergias')),
                ('Padecimientos', models.CharField(max_length=200, verbose_name='Padecimientos')),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dia', models.DateField()),
                ('Hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tratamiento', models.CharField(max_length=50, verbose_name='Tratamiento')),
                ('Descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreUsuario', models.CharField(max_length=30, verbose_name='Cuenta del usuario')),
                ('Contrasena', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('TipoEmpleado', models.CharField(choices=[('A', 'Administrador'), ('R', 'Recepcionista'), ('D', 'Doctor')], max_length=1, verbose_name='Tipo de empleado')),
                ('Nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('ApellidoPaterno', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('ApellidoMaterno', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('Genero', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1, verbose_name='Género')),
                ('Nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('Correo', models.EmailField(max_length=50, verbose_name='Correo electrónico')),
                ('Telefono', models.CharField(max_length=12, verbose_name='Telefono')),
                ('UltimoAcceso', models.DateTimeField(auto_now_add=True, verbose_name='Ultimo acceso al sistema')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nota', models.CharField(max_length=200, verbose_name='Nota')),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('Expedientepaciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Clinica.expedientepaciente', verbose_name='Expediente del paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinica.doctor', verbose_name='Doctor')),
                ('Tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinica.tratamiento', verbose_name='Tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Hora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Clinica.doctor', verbose_name='Doctor')),
                ('Hora', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Clinica.hora', verbose_name='Hora')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='Tratamientos',
            field=models.ManyToManyField(through='Clinica.Doctor_Tratamiento', to='Clinica.Tratamiento'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Clinica.usuario', verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(verbose_name='Fecha')),
                ('HoraInicio', models.TimeField()),
                ('HoraFin', models.TimeField()),
                ('Tratamiento', models.CharField(max_length=50, verbose_name='Tratamiento')),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('Expedientepaciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Clinica.expedientepaciente', verbose_name='Expediente del paciente')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Clinica.doctor', verbose_name='Doctor')),
            ],
        ),
    ]
