# Generated by Django 3.1.7 on 2021-05-25 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Especialidad', models.CharField(max_length=50, verbose_name='Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='ExpedientePaciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ApellidoPaterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('ApellidoMaterno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('Genero', models.CharField(max_length=10, verbose_name='Genero')),
                ('Telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('Direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('Nacimiento', models.DateField()),
                ('Correo', models.EmailField(max_length=254)),
                ('Alergias', models.CharField(max_length=50, verbose_name='Alergias')),
                ('Padecimientos', models.CharField(max_length=50, verbose_name='Padecimientos')),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dia', models.DateField()),
                ('Hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nota', models.CharField(max_length=50, verbose_name='Nota')),
                ('FechaCreacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tratamiento', models.CharField(max_length=50, verbose_name='Tratamiento')),
                ('Descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreUsuario', models.CharField(max_length=30, verbose_name='Cuenta del usuario')),
                ('Contraseña', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('TipoEmpleado', models.CharField(choices=[('A', 'Administrador'), ('R', 'Recepcionista'), ('D', 'Doctor')], max_length=1, verbose_name='Tipo de empleado')),
                ('Nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('ApellidoPaterno', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('ApellidoMaterno', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('Genero', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1, verbose_name='Género')),
                ('Nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('Correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('Telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('UltimoAcceso', models.DateTimeField(auto_now_add=True, verbose_name='Ultimo acceso al sistema')),
            ],
        ),
        migrations.CreateModel(
            name='Expediente_Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expedientepaciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Clinica.expedientepaciente', verbose_name='Expediente del paciente')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Clinica.nota', verbose_name='Nota')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Clinica.doctor', verbose_name='Doctor')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Clinica.tratamiento', verbose_name='Tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Hora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Clinica.doctor', verbose_name='Doctor')),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Clinica.hora', verbose_name='Hora')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Clinica.usuario', verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('HoraInicio', models.TimeField()),
                ('HoraFin', models.TimeField()),
                ('Tratamiento', models.CharField(max_length=50, verbose_name='Tratamiento')),
                ('FechaCreacion', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Clinica.doctor', verbose_name='Doctor')),
                ('expedientepaciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Clinica.expedientepaciente', verbose_name='Expediente del paciente')),
            ],
        ),
    ]
