# Generated by Django 3.1.7 on 2021-05-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ApellidoMaterno',
            field=models.CharField(blank=True, max_length=50, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ApellidoPaterno',
            field=models.CharField(blank=True, max_length=50, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Genero',
            field=models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Nacimiento',
            field=models.DateField(blank=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Nombres',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Telefono',
            field=models.CharField(max_length=12, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='TipoEmpleado',
            field=models.CharField(choices=[('A', 'Administrador'), ('R', 'Recepcionista'), ('D', 'Doctor')], default='A', max_length=1, verbose_name='Tipo de empleado'),
        ),
    ]
