# Generated by Django 3.1.7 on 2021-05-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0002_auto_20210530_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
