# Generated by Django 3.1.7 on 2021-06-06 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0002_auto_20210606_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='Tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinica.tratamiento', verbose_name='Tratamiento'),
        ),
    ]
