# Generated by Django 3.1.7 on 2021-05-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0002_auto_20210526_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Especialidad',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Especialidad'),
        ),
    ]
