# Generated by Django 3.1.7 on 2021-06-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0003_auto_20210606_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='Tratamiento',
            field=models.CharField(max_length=50, verbose_name='Tratamiento'),
        ),
    ]
